export TERMINAL="kitty"
export BROWSER="firefox-developer-edition"
export EDITOR="vim"
export FILE_EXPLORER="kitty -1 --class=files --name=filex --title=Ranger ranger"
export SCREENSHOT="flameshot gui"
